### ISSUE TITLE
Add Certbot DNS Challenge

### ISSUE THREAD

**Issue by fistwho** [pterodactyl-installer/pterodactyl-installer#374]
Hi :)

i would like to see an option for certbot dns plugins. So we can easy use Cloudflare without disable the proxying. 

https://certbot-dns-cloudflare.readthedocs.io/en/stable/

So mabye if you got time so please check this. 

Greets FiST

**Comment by Linux123123** [comment]
You can already use letsencrypt with Cloudflare proxy enabled, just that you need to forcefully continue on the DNS check step, which you can already skip too. 
Otherwise, it's the same and will work just as fine. Currently, I don't see a need to use a DNS challenge for the script, especially only adding the Cloudflare one.
That said, if we were to add it, a generic one would be more useful.
I am closing this for now, please reopen, if you have any other suggestions for this.
