### ISSUE TITLE
/dev/fd/61: line 122: composer: command not found

### ISSUE THREAD

**Issue by Louchou1** [pterodactyl-installer/pterodactyl-installer#385]
![image](https://user-images.githubusercontent.com/72306869/212679868-eaf8c628-0b3f-4769-a181-a7988f002e1d.png)

For two days, the installation script no longer works for me

**Comment by Linux123123** [comment]
Please provide your `$PATH`
```
echo $PATH
```

**Comment by Louchou1** [comment]
![image](https://user-images.githubusercontent.com/72306869/212901688-5ccbf642-895f-4e94-9ccd-483095e5366e.png)

**Comment by Linux123123** [comment]
Either login as root directly or use `sudo -i` to access root account.
This issue comes, when the correct paths are not loaded upon login to root account.

(Not directly script fault, but we should add all paths used to `$PATH` just in case of a situation like this)
Fix in script will come some time later.

**Comment by Louchou1** [comment]
Good ;)
