### ISSUE TITLE
Script fails to properly work with the mariadb

### ISSUE THREAD

**Issue by Whitescan** [pterodactyl-installer/pterodactyl-installer#391]
**Describe the bug**
When trying to install the panel, the script fails to access the mariadb.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the script
2. Select install option 2
3. Provide the required informations to the script until it asks for the DB password
4. Enter a custom password
5. See error (screenshot below)

**Expected behaviour**
The script should be able to access the database and execute it's commands.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/70441126/216776161-db48cda8-cc25-4dae-9666-d42073468276.png)

**OS (please complete the following information):**
Ubuntu 20.04 LTS
Installation: panel & wings on the same machine

**Additional context**
It works when using a random generated password.

**Comment by vilhelmprytz** [comment]
This is likely not a problem with the script, I'm guessing that you entered a password that is not escaped well with the `mysql` command we run in the script. It's bad design, I admit that since the script should tell you if you've entered something that won't work, but it's a corner case. And I don't think we really have the energy to solve it :(. Most people just use a random password. It would be interesting to know what type of password you entered that caused it to fail, please [join our Discord server](https://pterodactyl-installer.se/discord) and let us know.
