### ISSUE TITLE
Linux Mint Support

### ISSUE THREAD

**Issue by yegorsw** [pterodactyl-installer/pterodactyl-installer#444]
I am trying to use this script on Linux Mint and am getting an unsupported OS error. Since Linux Mint is based on Ubuntu, is it possibly to bypass the OS compatibility checks? Or are the differences large enough that it would not work?

**Comment by vilhelmprytz** [comment]
@yegorsw It would probably work just fine since, as you mentioned, it's based on Ubuntu. Unfortunately, we don't support Linux Mint since it's a desktop Linux distribution. If you are planning on setting up a server, I'd go with Ubuntu Server instead. If you really want the script to run on Mint, you can relatively easily modify the script to "think" that you are using Ubuntu. Closing for now!
